### ISSUE TITLE
Check for permission first and don't spam the log with unnecessary stacktraces

### ISSUE THREAD

**Issue by ts-twt** [cidaas/cidaas-android-sdk#14]
The SDK constantly tries to access the location, **without checking its permissios**!

This results to logs beeing constantly flooded with unusful stack traces.

![image](https://user-images.githubusercontent.com/61968062/78758475-7e4c6f00-797e-11ea-9b58-020f9972c4a7.png)

This should not happen!!!

Instead you should

1. only access location if enabled
2. check permissions before just trying to access location
3. don't always just log a full stacktrace, a warning like "no location permission granted" would be enough for an SKD like this

**Comment by cidaas** [comment]
Hi, 
Thank you for getting in touch. We are sorry that you are having trouble with the logs. This issue is handled in the latest update 2.0.2

**Comment by cidaas** [comment]
This is now resolved. We hope you will download our latest update, and continue. Truly appreciate your note and interest. Thank you!
